import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [pokemon, setPokemon] = useState(null);

  useEffect(() => {
    const abortController = new AbortController();

    fetch("https://pokeapi.co/api/v2/pokemon/ditto", {
      signal: abortController.signal,
    })
      .then((response) => response.json())
      .then((data) => setPokemon(data))
      .catch((error) => console.log(error.message));

    return () => {
      abortController.abort();
    };
  }, []);

  const imgSource =
    pokemon === null ? "" : pokemon.sprites.other.home.front_default;

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div
          className="container"
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
          }}
        >
          <img src={imgSource} className="hero-image" width="30%" />
          <div className="info">
            <p>{pokemon?.name}</p>
          </div>
        </div>
      </main>
    </div>
  );
}
